#!/usr/bin/env bash
# Provision the CockroachDB Cloud cluster used for the Managed MCP Server and the
# multi-region topology shots (the ccloud CLI is one of the four named sponsor tools).
#
# WHY A SECOND CLUSTER: you cannot kill a node in CockroachDB Cloud Basic/Standard -- there is
# no DB Console and crdb_internal is restricted by default (SQLSTATE 42501). The region-failure
# receipt therefore has to be filmed on a cluster we control (scripts/cluster-up.sh). This
# cloud cluster covers what local Docker cannot: the managed MCP endpoint and a genuine
# multi-region serverless topology. Two clusters, two purposes, both disclosed.
#
# Install:  brew install cockroachdb/tap/ccloud
#           (NOT `brew install ccloud` -- that formula is something else entirely)
set -euo pipefail

CLUSTER=${CLUSTER:-amnesia-proof}
REGIONS=${REGIONS:-us-east-1,us-west-2,eu-west-1}
PLAN=${PLAN:-basic}   # Basic: no credit card, ~$15/mo free, multi-region supported

hr() { printf '\n\033[1;33m%s\033[0m\n' "=== $* ==="; }

if ! command -v ccloud >/dev/null 2>&1; then
  echo "ccloud not installed. Run:  brew install cockroachdb/tap/ccloud" >&2
  exit 1
fi

hr "AUTH"
# Non-interactive when CC_API_KEY is exported; falls back to the browser flow otherwise.
if [ -n "${CC_API_KEY:-}" ]; then
  echo "using CC_API_KEY from the environment"
else
  ccloud auth login
fi

hr "CREATE CLUSTER ${CLUSTER} (${PLAN}, regions: ${REGIONS})"
# --json keeps the output machine-readable, which is what gets shown on camera: the CLI is a
# scored tool, so its structured output is worth surfacing rather than hiding behind a UI.
if ccloud cluster list --json 2>/dev/null | grep -q "\"name\": *\"${CLUSTER}\""; then
  echo "cluster ${CLUSTER} already exists — skipping create"
else
  ccloud cluster create "${PLAN}" "${CLUSTER}" --regions "${REGIONS}" --json
fi

hr "CLUSTER DETAILS"
ccloud cluster describe "${CLUSTER}" --json

hr "SQL USER"
# Password is generated by ccloud and printed once; capture it into your own secret store.
ccloud cluster user create "${CLUSTER}" amnesia --json || echo "(user may already exist)"

hr "CONNECTION STRING"
ccloud cluster sql "${CLUSTER}" --connection-string

cat <<'EOF'

Next:
  1. export CRDB_DSN='<the connection string above>'
  2. cockroach sql --url "$CRDB_DSN" -f sql/schema.sql
  3. Create a service-account API key in the Cloud console for the Managed MCP Server,
     export it as CRDB_API_KEY, then:  agent mcp

Note: run the chaos demo against the LOCAL cluster (scripts/cluster-up.sh). Cloud
Basic/Standard cannot kill a node, which is the whole point of that receipt.
EOF
