#!/usr/bin/env bash
# THE KILLER RECEIPT.
#
# Kills an entire CockroachDB region, then proves the agent's memory layer keeps working:
#   1. a write LANDS while the region is provably dead
#   2. a vector-index recall SUCCEEDS during the outage
#   3. on rejoin, the killed node serves back the exact row it was never alive to receive
#
# Why this can't be staged: the distances are irrational, the node table is generated by the
# database, and step 3's read is executed INSIDE the container that was killed.
#
# Reproduce:  ./scripts/cluster-up.sh && ./scripts/chaos.sh
set -euo pipefail

SQL() { docker exec -i roach1 ./cockroach sql --insecure -d agentmem "$@"; }
hr()  { printf '\n\033[1;33m%s\033[0m\n' "=== $* ==="; }

# 384-dim probe vector: 1 in the first position, 0 elsewhere.
PROBE="[$(python3 -c "print(','.join('1' if i==0 else '0' for i in range(384)))")]"

hr "PRE-OUTAGE BASELINE"
SQL -e "SELECT content, crdb_region FROM memories WHERE agent_id='agent_a1' ORDER BY created_at;"

hr "KILL ENTIRE REGION eu-west-1 (roach3)"
docker kill roach3 >/dev/null
echo "roach3 killed at $(date -u +%H:%M:%S)Z"

# TIMING PITFALL: is_live keeps reporting true for ~9-14s after the kill, until the node
# liveness lease expires. Reading the node table too early produces a screenshot that
# contradicts the claim. Wait it out.
echo -n "waiting ~16s for the liveness lease to expire"
for _ in $(seq 1 16); do sleep 1; echo -n .; done; echo

hr "NODE STATUS RECEIPT (node 3 must be is_available=false)"
docker exec roach1 ./cockroach node status --insecure --format=tsv 2>/dev/null \
  | awk 'BEGIN{OFS="\t"} NR==1{print "id","address","is_available","is_live"} NR>1{print $1,$2,$(NF-1),$NF}'

hr "WRITE DURING REGION OUTAGE"
# Pinned to a surviving region: eu-west-1's own replicas are gone, but quorum (2/3) holds,
# so the cluster still accepts writes. This is SURVIVE REGION FAILURE doing its job.
SQL -e "INSERT INTO memories (agent_id, kind, content, embedding, importance, crdb_region)
        VALUES ('agent_a1','episodic','WROTE DURING REGION OUTAGE','${PROBE}'::VECTOR(384),1.0,'us-east-1');"

hr "VECTOR RECALL DURING REGION OUTAGE"
# agent_id alone is pinned on purpose. Constraining crdb_region as well defeats the vector
# index (verified live) -- the planner then prefers a scan of the single-region span.
SQL -e "SELECT content, embedding <-> '${PROBE}'::VECTOR(384) AS dist
        FROM memories WHERE agent_id='agent_a1' ORDER BY 2 LIMIT 4;"

hr "BRING THE DEAD REGION BACK"
docker start roach3 >/dev/null
echo -n "waiting for roach3 to rejoin and catch up"
for _ in $(seq 1 20); do sleep 1; echo -n .; done; echo

hr "FINAL RECEIPT: read the outage-written row FROM THE NODE THAT WAS DEAD"
# Executed inside roach3 itself. It was not running when this row was written, so serving it
# back proves Raft replicated and self-healed rather than the row living only on survivors.
docker exec -i roach3 ./cockroach sql --insecure -d agentmem \
  -e "SELECT content, crdb_region, created_at FROM memories WHERE content LIKE 'WROTE%';"

hr "CLUSTER HEALTHY AGAIN"
docker exec roach1 ./cockroach node status --insecure --format=tsv 2>/dev/null \
  | awk 'BEGIN{OFS="\t"} NR==1{print "id","address","is_available","is_live"} NR>1{print $1,$2,$(NF-1),$NF}'
